INSERT INTO [dbo].[Camera] (Numero, Descrizione, Tipologia) VALUES
(101, 'Camera con vista sul mare', 'Singola'),
(102, 'Camera matrimoniale standard', 'Doppia'),
(103, 'Camera deluxe con balcone', 'Doppia'),
(104, 'Camera con vista sulla città', 'Singola'),
(105, 'Camera superior con jacuzzi', 'Doppia'),
(106, 'Camera economy', 'Singola'),
(107, 'Camera con letto king size', 'Doppia'),
(108, 'Camera familiare con due letti', 'Doppia'),
(109, 'Camera con terrazza privata', 'Doppia'),
(110, 'Camera con doccia a pioggia', 'Singola'),
(111, 'Camera con angolo cottura', 'Doppia'),
(112, 'Camera con vista sulla piscina', 'Doppia'),
(113, 'Camera romantica con letto a baldacchino', 'Doppia'),
(114, 'Camera con decorazioni moderne', 'Singola'),
(115, 'Camera standard con letti separati', 'Doppia');
