INSERT INTO [dbo].[Camere] ([NumeroCamera], [Descrizione], [Tipologia]) VALUES
(101, 'Camera con vista mare', 'doppia'),
(102, 'Camera standard', 'singola'),
(103, 'Camera deluxe', 'doppia'),
(104, 'Camera economica', 'singola'),
(105, 'Camera con balcone', 'doppia'),
(106, 'Camera con vista giardino', 'singola'),
(107, 'Camera suite', 'doppia'),
(108, 'Camera family', 'doppia'),
(109, 'Camera con minibar', 'doppia'),
(110, 'Camera romantica', 'singola'),
(111, 'Camera luxury', 'doppia'),
(112, 'Camera con jacuzzi', 'doppia'),
(113, 'Camera business', 'singola'),
(114, 'Camera con terrazzo', 'doppia'),
(115, 'Camera moderna', 'singola'),
(116, 'Camera con vista città', 'doppia'),
(117, 'Camera con angolo cottura', 'doppia'),
(118, 'Camera minimalista', 'singola'),
(119, 'Camera premium', 'doppia'),
(120, 'Camera con divano letto', 'doppia');